"""empty message

Revision ID: 16a2ce5430b7
Revises: 0cc8f0cf177b
Create Date: 2023-02-22 23:43:22.778775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a2ce5430b7'
down_revision = '0cc8f0cf177b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cylinders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('break_age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cylinders', schema=None) as batch_op:
        batch_op.drop_column('break_age')

    # ### end Alembic commands ###
