"""empty message

Revision ID: 48a0b111cfc7
Revises: bd37cf22c5cf
Create Date: 2023-02-23 23:10:39.800113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a0b111cfc7'
down_revision = 'bd37cf22c5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mix_used', schema=None) as batch_op:
        batch_op.alter_column('producer',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mix_used', schema=None) as batch_op:
        batch_op.alter_column('producer',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
