"""empty message

Revision ID: 57dbce0fafbb
Revises: ccf043a94f99
Create Date: 2023-02-20 17:52:44.218543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57dbce0fafbb'
down_revision = 'ccf043a94f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cylinders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recieved', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cylinders', schema=None) as batch_op:
        batch_op.drop_column('recieved')

    # ### end Alembic commands ###
