"""empty message

Revision ID: a0395b760c13
Revises: 16a2ce5430b7
Create Date: 2023-02-23 22:18:17.081791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0395b760c13'
down_revision = '16a2ce5430b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cylinders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_hold', sa.Boolean(), nullable=False))
        batch_op.alter_column('break_age',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('mix_design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('break_schedule', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mix_design', schema=None) as batch_op:
        batch_op.drop_column('break_schedule')

    with op.batch_alter_table('cylinders', schema=None) as batch_op:
        batch_op.alter_column('break_age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('on_hold')

    # ### end Alembic commands ###
