"""empty message

Revision ID: b5decd4e2b3d
Revises: 
Create Date: 2023-02-18 00:01:23.740435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5decd4e2b3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mix_used',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mix_description', sa.String(), nullable=True),
    sa.Column('mix_code', sa.String(), nullable=True),
    sa.Column('producer', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('isMRWH', sa.Boolean(), nullable=True),
    sa.Column('isHRWH', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slump', sa.Float(), nullable=True),
    sa.Column('air_content', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('ticket_number', sa.Integer(), nullable=True),
    sa.Column('total_cy', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('field_tech_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specimen_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('speciman_type', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cylinders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('max_load', sa.Integer(), nullable=True),
    sa.Column('dia1', sa.Float(), nullable=True),
    sa.Column('dia2', sa.Float(), nullable=True),
    sa.Column('break_strength', sa.Integer(), nullable=True),
    sa.Column('cylinder_type_id', sa.Integer(), nullable=True),
    sa.Column('break_type', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('lab_tech_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cylinder_type_id'], ['specimen_type.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mix_design',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producer', sa.Integer(), nullable=True),
    sa.Column('max_slump', sa.Float(), nullable=True),
    sa.Column('min_slump', sa.Float(), nullable=True),
    sa.Column('min_air_content', sa.Float(), nullable=True),
    sa.Column('max_air_content', sa.Float(), nullable=True),
    sa.Column('mid_range_max_slump', sa.Float(), nullable=True),
    sa.Column('mid_range_min_slump', sa.Float(), nullable=True),
    sa.Column('high_range_max_slump', sa.Float(), nullable=True),
    sa.Column('high_range_min_slump', sa.Float(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('design_strength', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mix_design')
    op.drop_table('cylinders')
    op.drop_table('specimen_type')
    op.drop_table('sets')
    op.drop_table('mix_used')
    # ### end Alembic commands ###
