"""empty message

Revision ID: bd37cf22c5cf
Revises: a0395b760c13
Create Date: 2023-02-23 22:44:48.950470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd37cf22c5cf'
down_revision = 'a0395b760c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('postalcode', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('cylinders', schema=None) as batch_op:
        batch_op.alter_column('cylinder_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('mix_design', schema=None) as batch_op:
        batch_op.alter_column('producer',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('mix_used', schema=None) as batch_op:
        batch_op.alter_column('isMRWH',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('isHRWH',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mix_used', schema=None) as batch_op:
        batch_op.alter_column('isHRWH',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('isMRWH',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('mix_design', schema=None) as batch_op:
        batch_op.alter_column('producer',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cylinders', schema=None) as batch_op:
        batch_op.alter_column('cylinder_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('projects')
    op.drop_table('clients')
    # ### end Alembic commands ###
