"""empty message

Revision ID: ccf043a94f99
Revises: b5decd4e2b3d
Create Date: 2023-02-18 00:34:37.477603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf043a94f99'
down_revision = 'b5decd4e2b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mix_design', schema=None) as batch_op:
        batch_op.drop_constraint('mix_design_set_id_fkey', type_='foreignkey')
        batch_op.drop_column('set_id')

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mix_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mix_used_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mix_design', ['mix_id'], ['id'])
        batch_op.create_foreign_key(None, 'mix_used', ['mix_used_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mix_used_id')
        batch_op.drop_column('mix_id')

    with op.batch_alter_table('mix_design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('mix_design_set_id_fkey', 'sets', ['set_id'], ['id'])

    # ### end Alembic commands ###
